Address reviews regarding the third section of the paper
geomstats/scipy_proceedings pull request #24
Opened 2020-06-18 09:38 UTC by Hzaatiti

We might need to discuss some comparison between k-medoid and k-means in the last part as requested by the reviewer ?

2020-06-18 17:14 UTC, ninamiolane requested changes
Great!! Thanks for your reactivity!! 🎉  A small comment about the use of `data_utils.load_karate_graph`.

For K-medoids, we can probably call the Scikit-Learn function on the dissimilarity matrix built using the hyperbolic metric?

https://scikit-learn-extra.readthedocs.io/en/latest/generated/sklearn_extra.cluster.KMedoids.html

2020-06-18 17:14 UTC, ninamiolane commented on papers/geomstats/geomstats.rst
> -    karate_graph = gdp.Graph(
Maybe still put:
`karate_graph = data_utils.load_karate_graph()`
somewhere in the paper?

This would show where the data come from and would be more consistent with the other tutorials, which use `data_utils.load_cities()` and `data_utils.load_connectomes`.

2020-06-18 17:14 UTC, ninamiolane commented on papers/geomstats/geomstats.rst
> +    +--------------+-----------------------------------------------------+-------+
Great! This was a very good suggestion indeed.

2020-06-19 13:26 UTC, Hzaatiti commented
> For K-medoids, we can probably call the Scikit-Learn function on the dissimilarity matrix built using the hyperbolic metric?
> 
> https://scikit-learn-extra.readthedocs.io/en/latest/generated/sklearn_extra.cluster.KMedoids.html

Do you mean to answer the reviewer comment or to try out in the example ? 
Looking at the fit function  of Kmedoid in scikit-learn-extra, it computes the dissimilarity matrix  D within it using one of the metrics from the scikit library (or those from scipy.spatial.distance). In its current implementation form it cannot take D as an input. (But I think it would be easy to have a similar class implemented in geomstats for Kmedoids ?)

2020-06-19 17:30 UTC, ninamiolane commented
@Hzaatiti answer to the reviewer + add it to the example? And only adding a mention of it in the scipy paper?

Sorry, I thought scikit-learn could take the dissimilarity matrix as input. Yes, a similar class in geomstats would be easy. @YannCabanes has implemented such classes for Riemannian KNN, etc.

2020-06-19 17:30 UTC, merged